[package]
name = "wasm_markdown_preview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
pulldown-cmark = "0.9.3"

[lib]
crate-type = ["cdylib", "rlib"]
